server:
  port: 8082

keycloak:
  realm: grow-me
  adminClientId: admin-cli
  adminClientSecret: RoJieZOMj83LPe0lllP2vO37xaXuKA75
  urls:
    auth: http://localhost:7080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/grow-me
  kafka:
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: keycloak-role-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

jwt:
  auth:
    converter:
      resource-id: authenticationClientId

logging:
  level:
    org.springframework.security: DEBUG
    org.keycloak: DEBUG

kafka:
  topics:
    role-assignment: user.role.assignments
    role-assignment-result: user.role.assignments.result