server:
  port: 8082



spring:
  config:
    activate:
      on-profile: dev
    import: optional:configserver:http://localhost:8888

logging:
  level:
    org.springframework.security: DEBUG
    org.keycloak: DEBUG

