server:
  port: 8082



spring:
  config:
    activate:
      on-profile: dev
    import: optional:configserver:http://localhost:8888

logging:
  level:
    org.springframework.security: DEBUG
    org.keycloak: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/