server:
  port: 8082

keycloak:
  realm: grow-me
  adminClientId: admin-cli
  adminClientSecret: z0eDUFAWjC1AkjPDfE8gfVwiORufyTQo
  urls:
    auth: http://localhost:7080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/grow-me
  kafka:
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
    consumer:
      group-id: keycloak-role-service
      properties:
        spring.json.trusted.packages: "*"

jwt:
  auth:
    converter:
      resource-id: authenticationClientId

logging:
  level:
    org.springframework.security: DEBUG
    org.keycloak: DEBUG

kafka:
  topics:
    role-assignment: user.role.assignments
    role-assignment-result: user.role.assignments.result
  consumer:
    group-id: keycloak-role-service