server:
  port: 8080

spring:
  application:
    name: gateway-server
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      lettuce:
        shutdown-timeout: 1s

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/grow-me
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowed-origins:
#              - "http://localhost:4200"
#            allowed-methods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#              - OPTIONS
#              - PATCH
#              - HEAD
#            allowed-headers:
#              - "*"
#            allow-credentials: true
#            max-age: 3600
#            exposed-headers:
#              - Authorization
#              - Content-Disposition
