server:
  port: 8080

spring:
  application:
    name: gateway-server
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:7080/realms/grow-me
#          jwk-set-uri: http://localhost:7080/realms/grow-me/protocol/openid-connect/certs
  config:
    import: configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
info:
  app:
    name: "gateway-server"
    description: "Grow-me-product-gateway-server"
    version: "1.0.0"

logging:
  level:
    com:
      home:
        gateway:
          server: DEBUG

