server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - name: TokenRelay
        - name: AddRequestHeader
          args:
            name: X-User-ID
            value: "{jwt:sub}"
        - name: AddRequestHeader
          args:
            name: X-User-Email
            value: "{jwt:email}"
        - name: AddRequestHeader
          args:
            name: X-User-Role
            value: "{jwt:realm_access.roles[0]}"
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
        - id: product-service
          uri: http://localhost:8079
          predicates:
            - Path=/products/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/grow-me
          jwk-set-uri: http://localhost:7080/realms/grow-me/protocol/openid-connect/certs

logging:
  level:
    org.springframework.security: DEBUG
