server:
  port: 8080

spring:
  application:
    name: gateway-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/grow-me
          jwk-set-uri: http://localhost:7080/realms/grow-me/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    gateway:
      access: unrestricted
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
info:
  app:
    name: "gateway-server"
    description: "Grow-me-product-gateway-server"
    version: "1.0.0"
