server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        -TokenRelay
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
           - Path=/users/**
