spring:
  application:
    name: preorder-service
  profiles:
    active: prod

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "preorder-service"
    description: "Grow-me-preorder-service-application"
    version: "1.0.0"
