server:
  port: 8086

spring:
  application:
    name: preorder-service
  datasource:
    url: jdbc:mysql://localhost:3306/growmepreorders?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hibernate.dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        generate_statistics: true
  sql:
    init:
      mode: never


