spring:
  application:
    name: payment-service
  config:
    activate:
      on-profile: prod
    import: configserver:http://config-server:8888
  kafka:
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        delivery.timeout.ms: 120000
        request.timeout.ms: 30000
        max.block.ms: 60000
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: payment-service
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: "com.home.growme.common.module.events.PaymentIntentRequestEvent"
server:
  port: 8084
