services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_DB_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
       - ./docker/mysql/init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh
       - ./docker/mysql/schema_user_service.sql:/docker-entrypoint-initdb.d/schema_user_service.sql
       - ./docker/mysql/schema_product_service.sql:/docker-entrypoint-initdb.d/schema_product_service.sql
       - ./docker/mysql/schema_order_service.sql:/docker-entrypoint-initdb.d/schema_order_service.sql
       - ./docker/mysql/schema_email_service.sql:/docker-entrypoint-initdb.d/schema_email_service.sql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$SQL_DB_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 10
    command: >
      --default-authentication-plugin=caching_sha2_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --explicit_defaults_for_timestamp=1
    networks:
      - grow-me

  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:8.0
    ports:
      - "3307:3306"
    volumes:
      - keycloak-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -p${KEYCLOAK_DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: ${KEYCLOAK_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${KEYCLOAK_DB_NAME}
      MYSQL_USER: ${KEYCLOAK_DB_USER}
      MYSQL_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    networks:
      - grow-me

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "7080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7080/realms/grow-me" ]
      interval: 10s
      timeout: 5s
      retries: 20
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: keycloak-mysql
      KC_DB_URL_PORT: 3306
      KC_DB_SCHEMA: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      KC_HEALTH_ENABLED: true

      KC_METRICS_ENABLED: true
      KC_LOG_LEVEL: INFO
      KC_FEATURES: scripts

      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: [ "start-dev","--import-realm" ]
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
    depends_on:
      keycloak-mysql:
        condition: service_healthy
    networks:
      - grow-me


  redis-cart:
    image: redis:latest
    container_name: cart-redis
    ports:
      - 6380:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 3
    command: [ "redis-server","--appendonly","yes" ]
    volumes:
      - redis-data:/data
    networks:
      - grow-me


  kafka-1:
    image: 'bitnami/kafka:latest'
    container_name: kafka-1
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_KRAFT_CLUSTER_ID=bba98d69-6a5d-4466-acc6-23b50e493beb
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9192,CONTROLLER://:9094,EXTERNAL://:9091
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9192,EXTERNAL://kafka-1:9091
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9094,2@kafka-2:9094,3@kafka-3:9094
    ports:
      - 9091:9091
    healthcheck:
      test: ["CMD", "bash", "-c", "echo dump | nc localhost 9192 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - kafka-1-data:/bitnami/kafka
    networks:
      - grow-me

  kafka-2:
    image: 'bitnami/kafka:latest'
    container_name: kafka-2
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_KRAFT_CLUSTER_ID=bba98d69-6a5d-4466-acc6-23b50e493beb
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9192,CONTROLLER://:9094,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9192,EXTERNAL://kafka-2:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9094,2@kafka-2:9094,3@kafka-3:9094
    ports:
      - 9092:9092
    healthcheck:
      test: ["CMD", "bash", "-c", "echo dump | nc localhost 9192 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - kafka-2-data:/bitnami/kafka
    networks:
      - grow-me

  kafka-3:
    image: 'bitnami/kafka:latest'
    container_name: kafka-3
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_KRAFT_CLUSTER_ID=bba98d69-6a5d-4466-acc6-23b50e493beb
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9192,CONTROLLER://:9094,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-3:9192,EXTERNAL://kafka-3:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9094,2@kafka-2:9094,3@kafka-3:9094
    ports:
      - 9093:9093
    healthcheck:
      test: ["CMD", "bash", "-c", "echo dump | nc localhost 9192 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - kafka-3-data:/bitnami/kafka
    networks:
      - grow-me

  config-server:
    image: tzetzaka2/config-server:v1
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      mysql:
        condition: service_healthy
      kafka-1:
        condition: service_completed_successfully
    healthcheck:
      test: "curl --fail --silent http://localhost:8888/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 1000M
    networks:
      - grow-me

  user-service:
    image: tzetzaka2/user-service:v1
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      config-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1000M
    networks:
      - grow-me
    environment:
      SPRING_APPLICATION_NAME: user-service
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8888"
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_USERNAME: ${SQL_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SQL_DB_PASSWORD}

  product-service:
    image: tzetzaka2/product-service:v1
    container_name: product-service
    ports:
      - "8087:8087"
    depends_on:
      config-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1000M
    networks:
      - grow-me
    environment:
      SPRING_APPLICATION_NAME: product-service
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8888"
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_USERNAME: ${SQL_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SQL_DB_PASSWORD}

  payment-service:
    image: tzetzaka2/payment-service:v1
    container_name: payment-service
    ports:
      - "8084:8084"
    depends_on:
      config-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1000M
    networks:
      - grow-me
    environment:
      SPRING_APPLICATION_NAME: payment-service
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8888"
      SPRING_PROFILES_ACTIVE: default
      STRIPE_API_KEY: ${STRIPE_API_KEY}

  order-service:
    image: tzetzaka2/order-service:v1
    container_name: order-service
    ports:
      - "8083:8083"
    depends_on:
      config-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
      redis-cart:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1000M
    networks:
      - grow-me
    environment:
      SPRING_APPLICATION_NAME: order-service
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8888"
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_USERNAME: ${SQL_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SQL_DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

  keycloak-service:
    image: tzetzaka2/keycloak-api:v1
    container_name: keycloak-service
    ports:
      - "8082:8082"
    depends_on:
      config-server:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      mysql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1000M
    environment:
      SPRING_APPLICATION_NAME: keycloak-service
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8888"
      SPRING_PROFILES_ACTIVE: default
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      JWT_AUTH_RESOURCE_ID: authenticationClientId
    networks:
      - grow-me


  email-service:
    image: tzetzaka2/email-service:v1
    container_name: email-service
    ports:
      - "8085:8085"
    depends_on:
      config-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1000M
    networks:
      - grow-me
    environment:
      SPRING_APPLICATION_NAME: email-service
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8888"
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SQL_DB_USERNAME: ${SQL_DB_USERNAME}
      SQL_DB_PASSWORD: ${SQL_DB_PASSWORD}


volumes:
  keycloak-mysql-data:
  keycloak_data:
  redis-data:
  kafka-1-data:
  kafka-2-data:
  kafka-3-data:

networks:
  grow-me:
    driver: "bridge"



