services:
  user-service:
    image: tzetzaka2/user-service:v1
    container_name: user-service
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 5000M
    networks:
      - growme

  product-service:
    image: tzetzaka2/product-service:v1
    container_name: product-service
    ports:
      - "8087:8087"
    deploy:
      resources:
        limits:
          memory: 5000M
    networks:
      - growme

  payment-service:
    image: tzetzaka2/payment-service:v1
    container_name: payment-service
    ports:
      - "8084:8084"
    deploy:
      resources:
        limits:
          memory: 5000M
    networks:
      - growme

  order-service:
    image: tzetzaka2/order-service:v1
    container_name: order-service
    ports:
      - "8083:8083"
    deploy:
      resources:
        limits:
          memory: 5000M
    networks:
      - growme

  keycloak-service:
    image: tzetzaka2/keycloak-api:v1
    container_name: keycloak-service
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 5000M
    networks:
      - growme

  email-service:
    image: tzetzaka2/email-service:v1
    container_name: order-service
    ports:
      - "8085:8085"
    deploy:
      resources:
        limits:
          memory: 5000M
    networks:
      - growme

networks:
  growme:
    driver: "bridge"