server:
  port: 8083

spring:
  data:
    redis:
      host: localhost
      port: 6380
  datasource:
    url: jdbc:mysql://localhost:3306/growmeorders?createDatabaseIfNotExist=true
    username: root
    password: password12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        generate_statistics: true
  sql:
    init:
      mode: never

