spring:
  application:
    name: order-service
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
info:
  app:
    name: "order-service"
    description: "Grow-me-order-service-application"
    version: "1.0.0"