server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/growmeproducts?createDatabaseIfNotExist=true
    username: root
    password: password12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: never


pagination:
  page:
    size:
      default: 12