server:
  port: 8087


spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/growmeproducts?createDatabaseIfNotExist=true
    username: ${SQL_DB_USERNAME}
    password: ${SQL_DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        generate_statistics: true
  sql:
    init:
        mode: always
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  kafka:
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: product-service
      properties:
        spring.json.trusted.packages: "*"


pagination:
  page:
    size:
      default: 12

app:
  upload:
    dir: uploads

