spring:
  application:
    name: product-service
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
info:
   app:
    name: "product-service"
    description: "Grow-me-product-service-application"
    version: "1.0.0"
