server:
  port: 8070

spring:
  application:
    name: eureka-server
  profiles:
    active: prod




management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

