package com.home.growme.common.module.enums;

public enum EmailType {

    PRODUCT_ADD_CONFIRMATION,
    ACCOUNT_DELETION_CONFIRMATION,
    ACCOUNT_COMPLETION_CONFIRMATION,
    ACCOUNT_UPDATE_CONFIRMATION
}
