package com.home.growme.common.module.enums;

public enum EmailType {

    //PRODUCT *** PRODUCT_SERVICE
    PRODUCT_ADD_CONFIRMATION,

    //ACCOUNT *** USER_SERVICE
    ACCOUNT_DELETION_CONFIRMATION,
    ACCOUNT_COMPLETION_CONFIRMATION,
    ACCOUNT_UPDATE_CONFIRMATION,

    //ORDER *** ORDER_SERVICE
    ORDER_CONFIRMATION,




    //TASK *** PREORDER_SERVICE
    TASK_CREATION_CONFIRMATION,
    TASK_STATUS_UPDATE,
    TASK_CANCELLATION_CONFIRMATION,

    //BID *** PREORDER_SERVICE
    BID_CREATION_CONFIRMATION,
    BID_WITHDRAWAL_CONFIRMATION,
    COUNTER_OFFER_NOTIFICATION,
    BID_STATUS_UPDATE,
    BID_ACTION_REQUIRED
}
