spring:
  application:
    name: config-server
  profiles:
    active: dev,native
  cloud:
    config:
      server:
        bootstrap: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true