server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DraganovTs/grow-me-config.git

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true


#        native:
#          search-locations: "classpath:/config"