
spring:
  application:
    name: email-service
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:3306/growmeemails?useSSL=false&allowPublicKeyRetrieval=true
    username: ${SQL_DB_USERNAME}
    password: ${SQL_DB_PASSWORD}
  kafka:
    consumer:
      group-id: email-service-group
  config:
    import: optional:configserver:http://config-server:8888/kafka-config.yml
sendgrid:
  api.key: ${SENDGRID_API_KEY:}
  from.email: ${SENDGRID_API_KEY:no-reply@growme.com}
  from.name: ${SENDGRID_API_NAME:GrowMe}
