
spring:
  application:
    name: email-service
  datasource:
    url: jdbc:mysql://localhost:3306/growmeemails?useSSL=false&allowPublicKeyRetrieval=true
    username: ${SQL_DB_USERNAME}
    password: ${SQL_DB_PASSWORD}
  kafka:
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        delivery.timeout.ms: 100000
        request.timeout.ms: 30000
        max.block.ms: 60000
        retries: 3
        acks: all
        enable.idempotence: true
        linger.ms: 5
        batch.size: 16384
        buffer.memory: 33554432
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        auto.offset.reset: earliest
        enable.auto.commit: false
      group-id: email-service-group
sendgrid:
  api.key: ${SENDGRID_API_KEY:}
  from.email: ${SENDGRID_API_KEY:no-reply@growme.com}
  from.name: ${SENDGRID_API_NAME:GrowMe}
