
spring:
  application:
    name: email-service
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:3306/growmeemails?useSSL=false&allowPublicKeyRetrieval=true
    username: ${SQL_DB_USERNAME}
    password: ${SQL_DB_PASSWORD}
  kafka:
    consumer:
      group-id: email-service-group
  config:
    import: configserver:http://config-server:8888/kafka-config-prod.yml
sendgrid:
  api.key: ${SENDGRID_API_KEY:}
  from.email: ${SENDGRID_API_KEY:no-reply@growme.com}
  from.name: ${SENDGRID_API_NAME:GrowMe}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/