
spring:
  application:
    name: email-service
  datasource:
    url: jdbc:mysql://localhost:3306/growmeemails?useSSL=false&allowPublicKeyRetrieval=true
    username: ${SQL_DB_USERNAME}
    password: ${SQL_DB_PASSWORD}
  kafka:
    consumer:
      group-id: email-service-group
  config:
    import: configserver:http://localhost:8888/kafka-config-dev.yml
sendgrid:
  api.key: ${SENDGRID_API_KEY:}
  from.email: ${SENDGRID_API_KEY:no-reply@growme.com}
  from.name: ${SENDGRID_API_NAME:GrowMe}
