spring:
  application:
    name: keycloak-role-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:7080/realms/grow-me
  kafka:
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        delivery.timeout.ms: 100000
        request.timeout.ms: 30000
        max.block.ms: 60000
        retries: 3
        acks: all
        enable.idempotence: true
        linger.ms: 5
        batch.size: 16384
        buffer.memory: 33554432
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        auto.offset.reset: earliest
        enable.auto.commit: false
      group-id: keycloak-role-service


jwt:
  auth:
    converter:
      resource-id: authenticationClientId