
spring:
  application:
    name: order-service
  data:
    redis:
      host: localhost
      port: 6380
  datasource:
    url: jdbc:mysql://localhost:3306/growmeorders?useSSL=false&allowPublicKeyRetrieval=true
    username: ${SQL_DB_USERNAME}
    password: ${SQL_DB_PASSWORD}
  kafka:
    consumer:
      group-id: order-service-group
  config:
    import: configserver:http://localhost:8888/kafka-config-dev.yml