
spring:
  application:
    name: order-service
  data:
    redis:
      host: ${REDIS_HOST:redis-cart}
      port: ${REDIS_PORT:6379}
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:3306/growmeorders?useSSL=false&allowPublicKeyRetrieval=true
    username: ${SQL_DB_USERNAME}
    password: ${SQL_DB_PASSWORD}
  kafka:
    consumer:
      group-id: order-service-group
  config:
    import: optional:configserver:http://config-server:8888/kafka-config-prod.yml