server:
  port: 8083

spring:
  application:
    name: order-service
  data:
    redis:
      host: localhost
      port: 6380
  datasource:
    url: jdbc:mysql://localhost:3306/growmeorders?createDatabaseIfNotExist=true
    username: ${SQL_DB_USERNAME}
    password: ${SQL_DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        generate_statistics: false
  sql:
    init:
      mode: never
      platform: mysql
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
