
spring:
  application:
    name: payment-service
  kafka:
    consumer:
      group-id: payment-service-group
  config:
    import: optional:configserver:http://config-server:8888/kafka-config-prod.yml
stripe:
  API_KEY: ${STRIPE_API_KEY}
