
spring:
  application:
    name: payment-service
  kafka:
    consumer:
      group-id: payment-service-group
  config:
    import: configserver:http://localhost:8888/kafka-config-dev.yml
stripe:
  API_KEY: ${STRIPE_API_KEY}
