
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:3306/growmeproducts?useSSL=false&allowPublicKeyRetrieval=true
    username: ${SQL_DB_USERNAME}
    password: ${SQL_DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 6MB
      max-request-size: 6MB
  kafka:
    consumer:
      group-id: product-service-group
pagination:
  page:
    size:
      default: 12
  config:
    import: configserver:http://config-server:8888/kafka-config-prod.yml
app:
  upload:
    dir: uploads

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/