
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/growmeproducts?useSSL=false&allowPublicKeyRetrieval=true
    username: ${SQL_DB_USERNAME}
    password: ${SQL_DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  kafka:
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        delivery.timeout.ms: 100000
        request.timeout.ms: 30000
        max.block.ms: 60000
        retries: 3
        ack: all
        enable.idempotence: true
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        auto.offset.reset: earliest
        enable.auto.commit: false
        isolation.level: read_committed
      group-id: product-service-group
    listener:
      ack-mode: MANUAL_IMMEDIATE
      missing-topics-fatal: false
  config:
    import: configserver:http://localhost:8888/kafka-config-dev.yml
pagination:
  page:
    size:
      default: 12
app:
  upload:
    dir: uploads
