
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:3306/growmeusers?useSSL=false&allowPublicKeyRetrieval=true
    username: ${SQL_DB_USERNAME}
    password: ${SQL_DB_PASSWORD}
  kafka:
    consumer:
      group-id: user-service-group
  config:
    import: configserver:http://config-server:8888/kafka-config-prod.yml

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8070/eureka/