
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/growmeusers?useSSL=false&allowPublicKeyRetrieval=true
    username: ${SQL_DB_USERNAME}
    password: ${SQL_DB_PASSWORD}
  kafka:
    consumer:
      group-id: user-service-group
#  config:
#    import: configserver:http://localhost:8888/kafka-config-dev.yml